apiVersion: v1
kind: Service
metadata:
  name: devday
  labels:
    run: devday
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: devday
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devday
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: devday
    spec:
      containers:
      - name: devday
        image: mesdevday.azurecr.io/devday
        ports:
        - containerPort: 80